_:
let
  # Pure Nix approach: Define p10k configuration as Nix strings
  # This recreates your custom p10k styling without external .zsh files

  customP10kConfig =
    "# Temporarily change options.\n"
    + "builtin local -a p10k_config_opts\n"
    + "[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')\n"
    + "[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')\n"
    + "[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')\n"
    + "builtin setopt no_aliases no_sh_glob brace_expand\n"
    + "\n"
    + "# Anonymous function definition\n"
    + "function {\n"
    + "  emulate -L zsh -o extended_glob\n"
    + "\n"
    + "  # Unset all configuration options. This allows you to apply configuration changes without\n"
    + "  # restarting zsh. Edit ~/.p10k.zsh and type \`source ~/.p10k.zsh\`.\n"
    + "  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'\n"
    + "\n"
    + "  # Zsh >= 5.1 is required.\n"
    + "  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return\n"
    + "\n"
    + "  # The list of segments shown on the left. Fill it with the most important segments.\n"
    + "  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(\n"
    + "    # =========================[ Line #1 ]=========================\n"
    + "    os_icon                 # os identifier\n"
    + "    dir                     # current directory\n"
    + "    vcs                     # git status\n"
    + "    # =========================[ Line #2 ]=========================\n"
    + "    newline                 # \\n\n"
    + "    prompt_char             # prompt symbol\n"
    + "  )\n"
    + "\n"
    + "  # The list of segments shown on the right. Fill it with less important segments.\n"
    + "  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(\n"
    + "      # =========================[ Line #1 ]=========================\n"
    + "      status                  # exit code of the last command\n"
    + "      command_execution_time  # duration of the last command\n"
    + "      background_jobs         # presence of background jobs\n"
    + "      direnv                  # direnv status (https://direnv.net/)\n"
    + "      asdf                    # asdf version manager (https://github.com/asdf-vm/asdf)\n"
    + "      virtualenv              # python virtual environment (https://docs.python.org/3/library/venv.html)\n"
    + "      anaconda                # conda environment (https://conda.io/)\n"
    + "      pyenv                   # python environment (https://github.com/pyenv/pyenv)\n"
    + "      goenv                   # go environment (https://github.com/syndbg/goenv)\n"
    + "      nodenv                  # node.js version from nodenv (https://github.com/nodenv/nodenv)\n"
    + "      nvm                     # node.js version from nvm (https://github.com/nvm-sh/nvm)\n"
    + "      nodeenv                 # node.js environment (https://github.com/ekalinin/nodeenv)\n"
    + "      # node_version          # node.js version\n"
    + "      # go_version            # go version (https://golang.org)\n"
    + "      # rust_version          # rustc version (https://www.rust-lang.org)\n"
    + "      # dotnet_version        # .NET version (https://dotnet.microsoft.com)\n"
    + "      # php_version           # php version (https://www.php.net/)\n"
    + "      # laravel_version       # laravel php framework version (https://laravel.com/)\n"
    + "      # java_version          # java version (https://www.java.com/)\n"
    + "      # package               # name@version from package.json (https://docs.npmjs.com/files/package.json)\n"
    + "      rbenv                   # ruby version from rbenv (https://github.com/rbenv/rbenv)\n"
    + "      rvm                     # ruby version from rvm (https://rvm.io)\n"
    + "      fvm                     # flutter version management (https://github.com/leoafarias/fvm)\n"
    + "      luaenv                  # lua version from luaenv (https://github.com/cehoffman/luaenv)\n"
    + "      jenv                    # java version from jenv (https://github.com/jenv/jenv)\n"
    + "      plenv                   # perl version from plenv (https://github.com/tokuhirom/plenv)\n"
    + "      perlbrew                # perl version from perlbrew (https://github.com/gugod/App-perlbrew)\n"
    + "      phpenv                  # php version from phpenv (https://github.com/phpenv/phpenv)\n"
    + "      scalaenv                # scala version from scalaenv (https://github.com/scalaenv/scalaenv)\n"
    + "      haskell_stack           # haskell version from stack (https://haskellstack.org/)\n"
    + "      kubecontext             # current kubernetes context (https://kubernetes.io/)\n"
    + "      terraform               # terraform workspace (https://www.terraform.io)\n"
    + "      # terraform_version     # terraform version (https://www.terraform.io)\n"
    + "      aws                     # aws profile (https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html)\n"
    + "      aws_eb_env              # aws elastic beanstalk environment (https://aws.amazon.com/elasticbeanstalk/)\n"
    + "      azure                   # azure account name (https://docs.microsoft.com/en-us/cli/azure)\n"
    + "      gcloud                  # google cloud cli account and project (https://cloud.google.com/)\n"
    + "      google_app_cred         # google application credentials (https://cloud.google.com/docs/authentication/production)\n"
    + "      toolbox                 # toolbox name (https://github.com/containers/toolbox)\n"
    + "      # context                 # user@hostname\n"
    + "      nordvpn                 # nordvpn connection status, linux only (https://nordvpn.com/)\n"
    + "      ranger                  # ranger shell (https://github.com/ranger/ranger)\n"
    + "      nnn                     # nnn shell (https://github.com/jarun/nnn)\n"
    + "      lf                      # lf shell (https://github.com/gokcehan/lf)\n"
    + "      xplr                    # xplr shell (https://github.com/sayanarijit/xplr)\n"
    + "      vim_shell               # vim shell indicator (:sh)\n"
    + "      midnight_commander      # midnight commander shell (https://midnight-commander.org/)\n"
    + "      nix_shell               # nix shell (https://nixos.org/nixos/nix-pills/developing-with-nix-shell.html)\n"
    + "      # vi_mode               # vi mode (you don't need this if you've enabled prompt_char)\n"
    + "      vpn_ip                # virtual private network indicator\n"
    + "      # load                  # CPU load\n"
    + "      # disk_usage            # disk usage\n"
    + "      # ram                   # free RAM\n"
    + "      # swap                  # used swap\n"
    + "      todo                    # todo items (https://github.com/todotxt/todo.txt-cli)\n"
    + "      timewarrior             # timewarrior tracking status (https://timewarrior.net/)\n"
    + "      taskwarrior             # taskwarrior task count (https://taskwarrior.org/)\n"
    + "      # cpu_arch              # CPU architecture\n"
    + "      time                    # current time\n"
    + "      # =========================[ Line #2 ]=========================\n"
    + "      newline\n"
    + "      ip                    # ip address and bandwidth usage for a specified network interface\n"
    + "      # public_ip             # public IP address\n"
    + "      # proxy                 # system-wide http/https/ftp proxy\n"
    + "      # battery               # internal battery\n"
    + "      # wifi                  # wifi speed\n"
    + "      # example               # example user-defined segment (see prompt_example function below)\n"
    + "  )\n"
    + "\n"
    + "  # Defines character set used by powerlevel10k. It's best to let \`p10k configure\` set it for you.\n"
    + "  typeset -g POWERLEVEL9K_MODE=awesome-fontconfig\n"
    + "\n"
    + "  # Add an empty line before each prompt.\n"
    + "  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false\n"
    + "  # Force prompt to clear properly\n"
    + "  typeset -g POWERLEVEL9K_SHOW_RULER=false\n"
    + "  # Enable transient prompt (makes old prompts minimal)\n"
    + "  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always\n"
    + "\n"
    + "  # Multiline prompt ornaments\n"
    + "  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''\n"
    + "  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=''\n"
    + "  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=''\n"
    + "\n"
    + "  # Right side ornaments instead (this is how your old prompt looked)\n"
    + "  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX='%242F─╮'\n"
    + "  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX='%242F─┤'\n"
    + "  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX='%242F─╯'\n"
    + "\n"
    + "  # Gap filler (the ····························· part)\n"
    + "  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR='·'\n"
    + "  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND=''\n"
    + "  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_GAP_BACKGROUND=''\n"
    + "  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=242\n"
    + "\n"
    + "  # Start/stop gap at screen edge when left/right segments are empty\n"
    + "  typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL='%{%}'\n"
    + "  typeset -g POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%{%}'\n"
    + "\n"
    + "  # The right end of left prompt.\n"
    + "  typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='▓▒░'\n"
    + "  # The left end of right prompt.\n"
    + "  typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='░▒▓'\n"
    + "\n"
    + "  # Remove end symbol from prompt character (second line)\n"
    + "  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''\n"
    + "\n"
    + "  # Segment seperator settings.\n"
    + "  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\\u2502'\n"
    + "  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\\u2502'\n"
    + "  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''\n"
    + "  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''\n"
    + "\n"
    + "  # OS identifier color.\n"
    + "  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=232\n"
    + "  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=7\n"
    + "  # Custom icon.\n"
    + "  # https://unicode.org/emoji/charts/full-emoji-list.html\n"
    + "  # Use logo nf-linux-nixos from nerdfonts: https://www.nerdfonts.com/cheat-sheet\n"
    + "  typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=$'\\uF313'\n"
    + "\n"
    + "  # Prompt char: prompt symbol\n"
    + "  # Transparent background.\n"
    + "  typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=\n"
    + "  # Green prompt symbol if the last command succeeded.\n"
    + "  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=76\n"
    + "  # Red prompt symbol if the last command failed.\n"
    + "  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=196\n"
    + "  # Default prompt symbol.\n"
    + "  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'\n"
    + "  # Prompt symbol in command vi mode.\n"
    + "  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'\n"
    + "  # Prompt symbol in visual vi mode.\n"
    + "  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='V'\n"
    + "  # Prompt symbol in overwrite vi mode.\n"
    + "  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'\n"
    + "  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true\n"
    + "  # No line terminator if prompt_char is the last segment.\n"
    + "  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=\n"
    + "  # No line introducer if prompt_char is the first segment.\n"
    + "  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=\n"
    + "  # No surrounding whitespace.\n"
    + "  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_{LEFT,RIGHT}_WHITESPACE=\n"
    + "\n"
    + "  # Directory colors.\n"
    + "  typeset -g POWERLEVEL9K_DIR_BACKGROUND='#A01F34'\n"
    + "  typeset -g POWERLEVEL9K_DIR_FOREGROUND=254\n"
    + "\n"
    + "  # Version control background colors.\n"
    + "  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=2\n"
    + "  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=3\n"
    + "  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=2\n"
    + "  typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND=3\n"
    + "  typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND=8\n"
    + "\n"
    + "  # Status colors.\n"
    + "  # Enable OK_PIPE, ERROR_PIPE and ERROR_SIGNAL status states to allow us to enable, disable and\n"
    + "  # style them independently from the regular OK and ERROR state.\n"
    + "  typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true\n"
    + "\n"
    + "  # Status on success. No content, just an icon. No need to show it if prompt_char is enabled as\n"
    + "  # it will signify success by turning green.\n"
    + "  typeset -g POWERLEVEL9K_STATUS_OK=false\n"
    + "  typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✔'\n"
    + "  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=2\n"
    + "  typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=0\n"
    + "\n"
    + "  # Status when some part of a pipe command fails but the overall exit status is zero. It may look\n"
    + "  # like this: 1|0.\n"
    + "  typeset -g POWERLEVEL9K_STATUS_OK_PIPE=true\n"
    + "  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION='✔'\n"
    + "  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=2\n"
    + "  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND=0\n"
    + "\n"
    + "  # Status when it's just an error code (e.g., '1'). No need to show it if prompt_char is enabled as\n"
    + "  # it will signify error by turning red.\n"
    + "  typeset -g POWERLEVEL9K_STATUS_ERROR=false\n"
    + "  typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✘'\n"
    + "  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=3\n"
    + "  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=1\n"
    + "\n"
    + "  # Status when the last command was terminated by a signal.\n"
    + "  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL=true\n"
    + "  # Use terse signal names: \"INT\" instead of \"SIGINT(2)\".\n"
    + "  typeset -g POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false\n"
    + "  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION='✘'\n"
    + "  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=3\n"
    + "  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=1\n"
    + "\n"
    + "  # Status when some part of a pipe command fails and the overall exit status is also non-zero.\n"
    + "  # It may look like this: 1|0.\n"
    + "  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true\n"
    + "  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION='✘'\n"
    + "  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=3\n"
    + "  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND=1\n"
    + "\n"
    + "  # Time colors.\n"
    + "  typeset -g POWERLEVEL9K_TIME_FOREGROUND=0\n"
    + "  typeset -g POWERLEVEL9K_TIME_BACKGROUND=7\n"
    + "  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%I:%M:%S %p}'\n"
    + "\n"
    + "  # IP colors.\n"
    + "  typeset -g POWERLEVEL9K_IP_BACKGROUND='#A01F34'\n"
    + "  typeset -g POWERLEVEL9K_IP_FOREGROUND=254\n"
    + "  typeset -g POWERLEVEL9K_IP_INTERFACE='[ew].*'\n"
    + "  # VPN IP color.\n"
    + "  typeset -g POWERLEVEL9K_VPN_IP_FOREGROUND=251 \n"
    + "  typeset -g POWERLEVEL9K_VPN_IP_BACKGROUND='#C2344B'\n"
    + "  # When on VPN, show just an icon without the IP address.\n"
    + "  # Tip: To display the private IP address when on VPN, remove the next line.\n"
    + "  #typeset -g POWERLEVEL9K_VPN_IP_CONTENT_EXPANSION=\n"
    + "  # Regular expression for the VPN network interface.\n"
    + "  typeset -g POWERLEVEL9K_VPN_IP_INTERFACE='(gpd|wg|(.*tun)|tailscale)[0-9]*'\n"
    + "  # Show all matching VPN interfaces.\n"
    + "  typeset -g POWERLEVEL9K_VPN_IP_SHOW_ALL=true\n"
    + "}\n"
    + "\n"
    + "(( \${#p10k_config_opts} )) && setopt \${p10k_config_opts[@]}\n"
    + "builtin unset p10k_config_opts\n";

  portableP10kConfig =
    "function {\n"
    + "  # Simple layout for TTY/portable terminals\n"
    + "  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(\n"
    + "    os_icon\n"
    + "    dir\n"
    + "    vcs\n"
    + "    newline\n"
    + "    prompt_char\n"
    + "  )\n"
    + "  \n"
    + "  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(\n"
    + "    status\n"
    + "    command_execution_time\n"
    + "    context\n"
    + "  )\n"
    + "  \n"
    + "  typeset -g POWERLEVEL9K_MODE=ascii\n"
    + "}\n";
in
{
  # Write pure Nix-defined p10k configs to home directory
  home.file = {
    ".p10k.zsh".text = customP10kConfig;
    ".p10k-portable.zsh".text = portableP10kConfig;
  };
}
