{ inputs, config, lib, pkgs, modulesPath, ... }:

{
  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
    git
    nix-index
    home-manager
    inputs.nix-alien.packages.${system}.nix-alien
    kdePackages.powerdevil
    file
    gparted
    tree
    vim
    nano
    wget
    unzip
    unrar
    htop
    btop
    gnumake
    cmake
    fastfetch
    lsb-release
    distrobox
    boxbuddy
    nmap
    socat
    rlwrap
    thefuck
    dfc
    zsh
    openvpn
    firefox-bin
    bloodhound
    bloodhound-py
    ffuf
    feroxbuster
    kerbrute
    smbmap
    wafw00f
    nikto
    commix
    davtest
    httrack
    joomscan
    whatweb
    sqlitebrowser
    cewl
    crunch
    evil-winrm-patched
    hashid
    hash-identifier
    hashcat
    john
    vscodium
    thc-hydra
    onesixtyone
    ncrack
    aircrack-ng
    reaverwps
    wifite2
    apktool
    cutter
    cutterPlugins.jsdec
    cutterPlugins.rz-ghidra
    edb
    ghidra-bin
    jadx
    radare2
    social-engineer-toolkit
    ettercap
    bettercap
    macchanger
    responder-patched
    tcpdump
    zeek
    proxychains-ng
    python311Packages.binwalk-full
    foremost
    scalpel
    pdf-parser
    pdfid
    soapui
    cryptsetup
    audacity
    dbeaver-bin
    filezilla
    ghex
    keepassxc
    powershell
    sonic-visualiser
    jq
    openldap
    ntp
    nfs-utils
    openssh
    dotnet-sdk_8
    dotnet-runtime_8
    dotnet-aspnetcore_8
    updog
    ngrok
    redis
    imagemagick
    strace
    # clamav broken at the moment
    #clamav
    dig
    steghide
    stegseek
    # xsser broken at the moment due to python nose
    #xsser
    lsd
    bat
    android-tools
    samba
    oletools
    exiftool
    man
    less
    whois
    exploitdb
    grc
    dnsenum
    dnsrecon
    libvncserver
    burpsuite
    ldapdomaindump
    certipy
    netexec
    enum4linux-ng
    wordlists
    rockyou
    metasploit
    sqlmap
    freerdp3
    pwndbg
    gef
    mariadb
    vesktop
    irssi
    telegram-desktop
    libreoffice-qt6-fresh
    freeoffice
    lshw
    lshw-gui
    krita
    mpv
    vlc
    pidgin
    thunderbird-bin
    tor-browser
    wineWowPackages.stable
    winetricks
    wineWowPackages.waylandFull
    bottles
    helvum
    python312Packages.impacket-patched
    mission-center
    wpscan
    joomscan
    psmisc
    # krdc broken: Unknown error
    #kdePackages.krdc
    remmina
    avalonia-ilspy
    aha
    pciutils
    clinfo
    glxinfo
    vulkan-tools
    wayland-utils
    python311Packages.patator
    jdk
    sqlcmd
    sqsh
  ];
}
